[autoexec]
mount c "C:\Development\CERBERUS"
mount d "C:\Development\CERBERUS\devenv"
c:
cerberus /ONLY:DET /NOINTRO /NOUI /NOUPLOAD /NICK:TESTNICK /O:D:\DBG.INI > D:\DBG.LOG
echo rc=%errorlevel% > D:\DBG.RC
exit
